---
- name: Configure central router
  hosts: centralRouter
  become: true
  tasks:
    - name: Enable forwarding
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
  roles:
    - role: mrlesmithjr.netplan
      netplan_enabled: true
      netplan_config_file: /etc/netplan/50-vagrant.yaml
      netplan_configuration:
        network:
          version: 2
          renderer: networkd
          ethernets:
            eth6:
              addresses:
                - 192.168.255.9/30
              routes:
                - to: 192.168.2.0/24
                  via: 192.168.255.10

              