---
- name: Configure office2 server
  hosts: office2Server
  become: true
  tasks:
    - name: Install traceroute
      ansible.builtin.apt:
        update_cache: true
        name: traceroute
  roles:
    - role: mrlesmithjr.netplan
      netplan_enabled: true
      netplan_config_file: /etc/netplan/60-vagrant.yaml
      netplan_configuration:
        network:
          version: 2
          renderer: networkd
          ethernets:
            enp0s3:
              dhcp4: true
              dhcp4-overrides:
                use-routes: false
              dhcp6: false
            enp0s8:
              routes:
                - to: default
                  via: 192.168.1.1
